[package]
name = "w6300-evb-pico2-json"
version = "0.1.0"
edition = "2024"

[dependencies]
cortex-m-rt = { version = "0.7.5", default-features = false }
defmt = { version = "1.0.1", default-features = false }
defmt-rtt = { version = "1.1.0", default-features = false }
panic-probe = { version = "1.0.0", default-features = false, features = ["print-defmt"] }
embedded-hal-bus = { version = "0.3.0", default-features = false, features = ["async"] }
static_cell = { version = "1.3.0", default-features = false }
serde = { version = "1.0.228", default-features = false }
serde-json-core = { version = "0.6.0", default-features = false }

embassy-rp = { version = "0.9.0", default-features = false, features = ["rp235xa", "critical-section-impl", "time-driver", "default"] }
embassy-time = { version = "0.5.0", default-features = false }
embassy-net = { version = "0.7.1", default-features = false, features = ["proto-ipv4", "medium-ethernet", "udp", "defmt"] }
embassy-net-wiznet = { version = "0.2.1", default-features = false, features = ["defmt"] }
embassy-executor = { version = "0.9.1", default-features = false, features = ["arch-cortex-m", "executor-thread"], optional = true }
embedded-hal-async = "1.0.0"

[dev-dependencies]
autospy = { version = "1.5.0", default-features = false }
tokio = { version = "1.48.0", default-features = false, features = ["macros", "rt"] }

[[bin]]
name = "w6300-evb-pico2-json"
required-features = ["arm"]

[features]
arm = ["dep:embassy-executor"]

[profile.release]
debug = 2 # provides DWARF info for probe-rs
lto = true
opt-level = 'z'

[patch.crates-io]
embassy-executor = { path = "../embassy/embassy-executor" }
embassy-time = { path = "../embassy/embassy-time" }
embassy-time-driver = { path = "../embassy/embassy-time-driver" }
embassy-rp = { path = "../embassy/embassy-rp" }
embassy-sync = { path = "../embassy/embassy-sync" }
embassy-futures = { path = "../embassy/embassy-futures" }
embassy-net-driver = { path = "../embassy/embassy-net-driver" }
embassy-net-driver-channel = { path = "../embassy/embassy-net-driver-channel" }
embassy-net-wiznet = { path = "../embassy/embassy-net-wiznet" }